export const notifications = {
  place: 'orders',
  acceptOrder: 'orders',
  cancelOrder: 'orders',
  updateOrder: 'orders',
  shipmentRequested: 'shipments',
  shipmentConfirmed: 'shipments',
  validateProof: 'proofs',
  proofGenerated: 'proofs',
  contractCreated: 'contracts',
  placeInvoice: 'invoices',
  acceptInvoice: 'invoices',
  placeBid: 'bids',
  acceptBid: 'bids',
  editBid: 'bids',
  documentUploaded: 'shipments',
  invoiceRegistered: 'invoices',
  reportGenerated: 'reports',
  invoiceRemoved: 'invoices'
};

export const title = {
  place: 'Order Created',
  acceptOrder: 'Order Accepted',
  cancelOrder: 'Order Cancelled',
  updateOrder: 'Order Updated',
  shipmentRequested: 'Shipment Requested',
  shipmentConfirmed: 'Shipment Confirmed',
  shipmentDelivered: 'Shipment Delivered',
  validateProof: 'Proof Validated',
  proofGenerated: 'Proof Generated',
  contractCreated: 'Contract Created',
  acceptInvoice: 'Invoice Accepted',
  placeBid: 'Bid Placed',
  acceptBid: 'Bid Accepted',
  editBid: 'Bid Updated',
  documentUploaded: 'Document Uploaded',
  invoiceRegistered: 'Invoice Registered',
  cancelBid: 'Bid Cancelled',
  placeInvoice: 'Invoice Signed',
  reportGenerated: 'Report Created',
  invoiceRemoved: 'Invoice Removed'
};
